# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addstaff.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_add_staff(object):
    def setupUi(self, add_staff):
        add_staff.setObjectName("add_staff")
        add_staff.resize(915, 569)
        add_staff.setStyleSheet("background-color:#f4f9f4;")
        self.label_3 = QtWidgets.QLabel(add_staff)
        self.label_3.setGeometry(QtCore.QRect(450, 200, 61, 21))
        self.label_3.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_3.setObjectName("label_3")
        self.qingkong = QtWidgets.QPushButton(add_staff)
        self.qingkong.setGeometry(QtCore.QRect(510, 420, 75, 23))
        self.qingkong.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qingkong.setStyleSheet("font:75 10pt \"黑体\";\n"
"color:white;\n"
"background-color:rgb(85,170,127);\n"
"border-radius:3px;")
        self.qingkong.setObjectName("qingkong")
        self.email = QtWidgets.QLineEdit(add_staff)
        self.email.setGeometry(QtCore.QRect(520, 160, 101, 21))
        self.email.setText("")
        self.email.setObjectName("email")
        self.label_7 = QtWidgets.QLabel(add_staff)
        self.label_7.setGeometry(QtCore.QRect(240, 280, 61, 21))
        self.label_7.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(add_staff)
        self.label_12.setGeometry(QtCore.QRect(450, 240, 61, 21))
        self.label_12.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_12.setObjectName("label_12")
        self.name = QtWidgets.QLineEdit(add_staff)
        self.name.setGeometry(QtCore.QRect(310, 120, 101, 21))
        self.name.setObjectName("name")
        self.label_8 = QtWidgets.QLabel(add_staff)
        self.label_8.setGeometry(QtCore.QRect(240, 200, 61, 21))
        self.label_8.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_8.setObjectName("label_8")
        self.major = QtWidgets.QLineEdit(add_staff)
        self.major.setGeometry(QtCore.QRect(520, 400, 101, 21))
        self.major.setText("")
        self.major.setObjectName("major")
        self.professional = QtWidgets.QComboBox(add_staff)
        self.professional.setGeometry(QtCore.QRect(520, 280, 101, 22))
        self.professional.setEditable(False)
        self.professional.setCurrentText("")
        self.professional.setObjectName("professional")
        self.graduate_time = QtWidgets.QDateEdit(add_staff)
        self.graduate_time.setGeometry(QtCore.QRect(520, 360, 101, 21))
        self.graduate_time.setWrapping(False)
        self.graduate_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.graduate_time.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1754, 9, 14), QtCore.QTime(0, 0, 0)))
        self.graduate_time.setCalendarPopup(True)
        self.graduate_time.setDate(QtCore.QDate(2018, 1, 1))
        self.graduate_time.setObjectName("graduate_time")
        self.label = QtWidgets.QLabel(add_staff)
        self.label.setGeometry(QtCore.QRect(240, 120, 61, 21))
        self.label.setStyleSheet("font: 10pt \"幼圆\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(add_staff)
        self.lineEdit.setGeometry(QtCore.QRect(390, 40, 121, 21))
        self.lineEdit.setStyleSheet("font: 14pt \"华文行楷\";\n"
"color:rgb(80, 126, 59);\n"
"background-color:transparent;\n"
"border:outset;")
        self.lineEdit.setObjectName("lineEdit")
        self.salary = QtWidgets.QSpinBox(add_staff)
        self.salary.setGeometry(QtCore.QRect(520, 320, 101, 21))
        self.salary.setMaximum(100000)
        self.salary.setSingleStep(100)
        self.salary.setProperty("value", 0)
        self.salary.setObjectName("salary")
        self.label_major = QtWidgets.QLabel(add_staff)
        self.label_major.setGeometry(QtCore.QRect(450, 400, 61, 21))
        self.label_major.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_major.setObjectName("label_major")
        self.label_4 = QtWidgets.QLabel(add_staff)
        self.label_4.setGeometry(QtCore.QRect(240, 160, 61, 21))
        self.label_4.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_4.setObjectName("label_4")
        self.department = QtWidgets.QComboBox(add_staff)
        self.department.setGeometry(QtCore.QRect(310, 320, 101, 22))
        self.department.setEditable(False)
        self.department.setCurrentText("")
        self.department.setObjectName("department")
        self.identity = QtWidgets.QLineEdit(add_staff)
        self.identity.setGeometry(QtCore.QRect(310, 160, 101, 21))
        self.identity.setObjectName("identity")
        self.add = QtWidgets.QPushButton(add_staff)
        self.add.setGeometry(QtCore.QRect(310, 420, 75, 23))
        self.add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add.setStyleSheet("font:75 10pt \"黑体\";\n"
"color:white;\n"
"background-color:rgb(85,170,127);\n"
"border-radius:3px;")
        self.add.setObjectName("add")
        self.birth = QtWidgets.QDateEdit(add_staff)
        self.birth.setGeometry(QtCore.QRect(520, 200, 101, 21))
        self.birth.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.birth.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.birth.setWrapping(False)
        self.birth.setFrame(True)
        self.birth.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.birth.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.birth.setCalendarPopup(True)
        self.birth.setDate(QtCore.QDate(2018, 1, 1))
        self.birth.setObjectName("birth")
        self.address = QtWidgets.QLineEdit(add_staff)
        self.address.setGeometry(QtCore.QRect(310, 200, 101, 21))
        self.address.setText("")
        self.address.setObjectName("address")
        self.label_14 = QtWidgets.QLabel(add_staff)
        self.label_14.setGeometry(QtCore.QRect(450, 280, 61, 21))
        self.label_14.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_14.setObjectName("label_14")
        self.label_school = QtWidgets.QLabel(add_staff)
        self.label_school.setGeometry(QtCore.QRect(240, 400, 61, 21))
        self.label_school.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_school.setObjectName("label_school")
        self.sex = QtWidgets.QComboBox(add_staff)
        self.sex.setGeometry(QtCore.QRect(310, 240, 101, 21))
        self.sex.setEditable(False)
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.sex.addItem("")
        self.label_13 = QtWidgets.QLabel(add_staff)
        self.label_13.setGeometry(QtCore.QRect(240, 320, 61, 21))
        self.label_13.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(add_staff)
        self.label_11.setGeometry(QtCore.QRect(240, 360, 61, 21))
        self.label_11.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_11.setObjectName("label_11")
        self.school = QtWidgets.QLineEdit(add_staff)
        self.school.setGeometry(QtCore.QRect(310, 400, 101, 21))
        self.school.setObjectName("school")
        self.label_17 = QtWidgets.QLabel(add_staff)
        self.label_17.setGeometry(QtCore.QRect(450, 320, 61, 21))
        self.label_17.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_17.setObjectName("label_17")
        self.tel = QtWidgets.QLineEdit(add_staff)
        self.tel.setGeometry(QtCore.QRect(520, 120, 101, 21))
        self.tel.setObjectName("tel")
        self.label_5 = QtWidgets.QLabel(add_staff)
        self.label_5.setGeometry(QtCore.QRect(450, 120, 61, 21))
        self.label_5.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_5.setObjectName("label_5")
        self.isMarried = QtWidgets.QComboBox(add_staff)
        self.isMarried.setGeometry(QtCore.QRect(310, 280, 101, 22))
        self.isMarried.setEditable(False)
        self.isMarried.setObjectName("isMarried")
        self.isMarried.addItem("")
        self.isMarried.addItem("")
        self.isMarried.addItem("")
        self.label_time = QtWidgets.QLabel(add_staff)
        self.label_time.setGeometry(QtCore.QRect(450, 360, 61, 21))
        self.label_time.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_time.setObjectName("label_time")
        self.label_6 = QtWidgets.QLabel(add_staff)
        self.label_6.setGeometry(QtCore.QRect(450, 160, 61, 21))
        self.label_6.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(add_staff)
        self.label_2.setGeometry(QtCore.QRect(240, 240, 61, 21))
        self.label_2.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.entry_time = QtWidgets.QDateEdit(add_staff)
        self.entry_time.setGeometry(QtCore.QRect(520, 240, 101, 21))
        self.entry_time.setWrapping(False)
        self.entry_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.entry_time.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1754, 9, 14), QtCore.QTime(0, 0, 0)))
        self.entry_time.setCalendarPopup(True)
        self.entry_time.setDate(QtCore.QDate(2018, 1, 1))
        self.entry_time.setObjectName("entry_time")
        self.xl = QtWidgets.QComboBox(add_staff)
        self.xl.setGeometry(QtCore.QRect(310, 360, 101, 22))
        self.xl.setEditable(False)
        self.xl.setObjectName("xl")
        self.xl.addItem("")
        self.xl.addItem("")
        self.xl.addItem("")
        self.xl.addItem("")
        self.xl.addItem("")
        self.xl.addItem("")
        self.xl.addItem("")
        self.label_3.setBuddy(self.birth)
        self.label_7.setBuddy(self.isMarried)
        self.label_12.setBuddy(self.entry_time)
        self.label_8.setBuddy(self.address)
        self.label.setBuddy(self.name)
        self.label_major.setBuddy(self.major)
        self.label_4.setBuddy(self.identity)
        self.label_14.setBuddy(self.professional)
        self.label_school.setBuddy(self.school)
        self.label_13.setBuddy(self.department)
        self.label_11.setBuddy(self.xl)
        self.label_17.setBuddy(self.salary)
        self.label_5.setBuddy(self.tel)
        self.label_time.setBuddy(self.graduate_time)
        self.label_6.setBuddy(self.email)
        self.label_2.setBuddy(self.sex)

        self.retranslateUi(add_staff)
        self.add.clicked.connect(add_staff.addInfo)
        self.qingkong.clicked.connect(add_staff.clearAll)
        self.xl.currentTextChanged['QString'].connect(add_staff.showDetail)
        QtCore.QMetaObject.connectSlotsByName(add_staff)

    def retranslateUi(self, add_staff):
        _translate = QtCore.QCoreApplication.translate
        add_staff.setWindowTitle(_translate("add_staff", "Form"))
        self.label_3.setText(_translate("add_staff", "出生日期："))
        self.qingkong.setText(_translate("add_staff", "清空"))
        self.label_7.setText(_translate("add_staff", "婚否："))
        self.label_12.setText(_translate("add_staff", "入职时间："))
        self.label_8.setText(_translate("add_staff", "住址："))
        self.graduate_time.setDisplayFormat(_translate("add_staff", "yyyy-MM-dd"))
        self.label.setText(_translate("add_staff", "员工姓名："))
        self.lineEdit.setText(_translate("add_staff", "添加员工信息"))
        self.label_major.setText(_translate("add_staff", "专业："))
        self.label_4.setText(_translate("add_staff", "身份证号："))
        self.add.setText(_translate("add_staff", "添加"))
        self.birth.setDisplayFormat(_translate("add_staff", "yyyy-MM-dd"))
        self.label_14.setText(_translate("add_staff", "职位："))
        self.label_school.setText(_translate("add_staff", "毕业院校："))
        self.sex.setCurrentText(_translate("add_staff", "-请选择"))
        self.sex.setItemText(0, _translate("add_staff", "-请选择"))
        self.sex.setItemText(1, _translate("add_staff", "男"))
        self.sex.setItemText(2, _translate("add_staff", "女"))
        self.label_13.setText(_translate("add_staff", "所在部门："))
        self.label_11.setText(_translate("add_staff", "学历："))
        self.label_17.setText(_translate("add_staff", "薪资："))
        self.label_5.setText(_translate("add_staff", "电话："))
        self.isMarried.setCurrentText(_translate("add_staff", "-请选择"))
        self.isMarried.setItemText(0, _translate("add_staff", "-请选择"))
        self.isMarried.setItemText(1, _translate("add_staff", "是"))
        self.isMarried.setItemText(2, _translate("add_staff", "否"))
        self.label_time.setText(_translate("add_staff", "毕业时间："))
        self.label_6.setText(_translate("add_staff", "邮箱："))
        self.label_2.setText(_translate("add_staff", "性别："))
        self.entry_time.setDisplayFormat(_translate("add_staff", "yyyy-MM-dd"))
        self.xl.setCurrentText(_translate("add_staff", "-请选择"))
        self.xl.setItemText(0, _translate("add_staff", "-请选择"))
        self.xl.setItemText(1, _translate("add_staff", "初中及以下"))
        self.xl.setItemText(2, _translate("add_staff", "高中"))
        self.xl.setItemText(3, _translate("add_staff", "中专"))
        self.xl.setItemText(4, _translate("add_staff", "大专"))
        self.xl.setItemText(5, _translate("add_staff", "本科"))
        self.xl.setItemText(6, _translate("add_staff", "研究生"))

