# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dept_detail.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dept_detail(object):
    def setupUi(self, dept_detail):
        dept_detail.setObjectName("dept_detail")
        dept_detail.resize(917, 571)
        dept_detail.setStyleSheet("background-color:#f4f9f4;")
        self.back = QtWidgets.QPushButton(dept_detail)
        self.back.setEnabled(True)
        self.back.setGeometry(QtCore.QRect(60, 30, 31, 31))
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setStyleSheet("border-image: url(:/newPrefix/images/back.png);")
        self.back.setText("")
        self.back.setObjectName("back")
        self.lineEdit = QtWidgets.QLineEdit(dept_detail)
        self.lineEdit.setGeometry(QtCore.QRect(390, 40, 121, 21))
        self.lineEdit.setStyleSheet("font: 14pt \"华文行楷\";\n"
"color:rgb(80, 126, 59);\n"
"background-color:transparent;\n"
"border:outset;")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(dept_detail)
        self.label.setGeometry(QtCore.QRect(320, 80, 81, 31))
        self.label.setStyleSheet("font: 11pt \"幼圆\";")
        self.label.setObjectName("label")
        self.name = QtWidgets.QLineEdit(dept_detail)
        self.name.setGeometry(QtCore.QRect(400, 80, 91, 31))
        self.name.setStyleSheet("border:outset;")
        self.name.setText("")
        self.name.setObjectName("name")
        self.manager = QtWidgets.QLineEdit(dept_detail)
        self.manager.setGeometry(QtCore.QRect(590, 80, 71, 31))
        self.manager.setStyleSheet("border:outset;")
        self.manager.setText("")
        self.manager.setObjectName("manager")
        self.label_2 = QtWidgets.QLabel(dept_detail)
        self.label_2.setGeometry(QtCore.QRect(500, 80, 81, 31))
        self.label_2.setStyleSheet("font: 11pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(dept_detail)
        self.label_9.setGeometry(QtCore.QRect(150, 80, 81, 31))
        self.label_9.setStyleSheet("font: 11pt \"幼圆\";")
        self.label_9.setObjectName("label_9")
        self.no = QtWidgets.QLineEdit(dept_detail)
        self.no.setEnabled(False)
        self.no.setGeometry(QtCore.QRect(230, 80, 81, 31))
        self.no.setStyleSheet("border:outset;\n"
"background:transparent;\n"
"")
        self.no.setText("")
        self.no.setObjectName("no")
        self.num = QtWidgets.QLineEdit(dept_detail)
        self.num.setGeometry(QtCore.QRect(800, 80, 81, 31))
        self.num.setStyleSheet("border:outset;")
        self.num.setText("")
        self.num.setObjectName("num")
        self.tableWidget = QtWidgets.QTableWidget(dept_detail)
        self.tableWidget.setGeometry(QtCore.QRect(150, 190, 611, 321))
        self.tableWidget.setStyleSheet("border:outset;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(203)
        self.tableWidget.verticalHeader().setVisible(False)
        self.lineEdit_3 = QtWidgets.QLineEdit(dept_detail)
        self.lineEdit_3.setGeometry(QtCore.QRect(380, 140, 161, 31))
        self.lineEdit_3.setStyleSheet("font: 13pt \"黑体\";\n"
"color:rgb(80, 126, 59);\n"
"border:outset;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(dept_detail)
        self.label_3.setGeometry(QtCore.QRect(670, 80, 121, 31))
        self.label_3.setStyleSheet("font: 11pt \"幼圆\";\n"
"border:outset;")
        self.label_3.setObjectName("label_3")
        self.label.setBuddy(self.name)
        self.label_2.setBuddy(self.manager)
        self.label_9.setBuddy(self.no)
        self.label_3.setBuddy(self.num)

        self.retranslateUi(dept_detail)
        self.back.clicked.connect(dept_detail.goback)
        QtCore.QMetaObject.connectSlotsByName(dept_detail)

    def retranslateUi(self, dept_detail):
        _translate = QtCore.QCoreApplication.translate
        dept_detail.setWindowTitle(_translate("dept_detail", "Form"))
        self.lineEdit.setText(_translate("dept_detail", "部门详细信息"))
        self.label.setText(_translate("dept_detail", "部门名称："))
        self.label_2.setText(_translate("dept_detail", "部门经理："))
        self.label_9.setText(_translate("dept_detail", "部门编号："))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("dept_detail", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("dept_detail", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("dept_detail", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("dept_detail", "3"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("dept_detail", "工号"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("dept_detail", "姓名"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("dept_detail", "详细信息"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit_3.setText(_translate("dept_detail", "该部门所有员工表"))
        self.label_3.setText(_translate("dept_detail", "该部门员工总数:"))

import img_rc
